# Generated by Django 5.2 on 2025-04-28 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=9)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('client_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estimated_distance', models.DecimalField(decimal_places=15, default=0, max_digits=20)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pendiente'), ('in_transit', 'En Tránsito'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=50)),
                ('address_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addressmodel')),
                ('driver_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drivermodel')),
            ],
        ),
    ]
